### ISSUE TITLE
Implementing Anti-Ban System in Scripts

### ISSUE THREAD

**Issue by xYuri** [the-reminisce/simplebot#6]
Request: A method to listen to the ANTI-BAN system events (Staff Nearby) Like: [Log Screenshot](https://i.ibb.co/NNnBKdD/Screenshot-35.png)

`isStaffNearby();` return boolean
`getStaffNearby();` return String[] staffList

Maybe added in simple.robot.utils

**Comment by the-reminisce** [comment]
Completed `ctx.antiBan`
